AllCops:
  Exclude:
    - README.md
    - bento_qemu.gemspec
    - .bundle*:/**/*
    - .vendor/**/*
    - vendor/**/*
    - bundl*/**/*

Documentation:
  Enabled: false

EmptyLinesAroundBody:
  Enabled: false

HashSyntax:
  EnforcedStyle: hash_rockets

RegexpLiteral:
  MaxSlashes: 0

Style/MethodLength:
  Max: 20

# inherit_from: .rubocop_todo.yml
