AllCops:
  Exclude:
    - README.md
    - bento_qemu.gemspec

Documentation:
  Enabled: false

EmptyLinesAroundBody:
  Enabled: false

HashSyntax:
  EnforcedStyle: hash_rockets

RegexpLiteral:
  MaxSlashes: 0

inherit_from: .rubocop_todo.yml
