language: ruby
rvm:
  - 2.0.0

before_install:
  - wget --no-check-certificate https://dl.bintray.com/mitchellh/packer/0.6.0_linux_amd64.zip
  - unzip -d packer 0.6.0_linux_amd64.zip

before_script: export PATH=$PATH:$PWD/packer

script: bundle exec thor bento-qemu:invoke_from_yaml('./.travis_tasks.yml')

